version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    env_file: database/database.conf
    environment:
      - APP_NAME=RateMyMolecule
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  database:
    container_name: postgres
    image: postgres:latest
    
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: