version: "3.7"

services:

  nginx:
    container_name: rmm/nginx
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80

  flask:
    container_name: rmm/flask
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=RateMyMolecule
      - DATABASE_URL=postgres://stevenbennett:password@postgres:5432/ratemymolecule
    expose:
      - 8080

  database:
    container_name: rmm/database
    env_file: 
      - database/database.conf
    build: ./database
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: