version: "3.7"

services:

  nginx:
    container_name: nginx
    build: ./nginx
    volumes: 
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: always
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    volumes:
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot

  flask:
    container_name: flask
    env_file: 
      - database/database.conf
      - docker_env.env
    build: ./flask
    restart: always
    environment:
      - APP_NAME=RateMyMolecule
      - FLASK_ENV=production
      - DATABASE_URL=postgres://example:password@database:5432/example
    expose:
      - 8080

  database:
    container_name: database
    env_file: 
      - database/database.conf
    build: ./database
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: